### ISSUE TITLE
Incorrectly flags `false` prop values as strings marked for translation

### ISSUE THREAD

**Issue by joncursi** [ramivalta/eslint-plugin-react-intl#6]
```jsx
<Component
   prop={false} // <-- this will error with react-intl/string-is-marked-for-translation
/>
```

**Comment by grahamlyus** [comment]
@joncursi Are you using `babel-eslint`? 

I had upgraded `babel-eslint` to 8.0.0, and was seeing the same/similar errors. Downgrading back to 7.1.1 seems to solve the problem. I don't think the problem lies with this plugin.

**Comment by joncursi** [comment]
Hmm... I am indeed on `babel-eslint@latest`.

**Comment by Slumber86** [comment]
I Read that babel-eslint 8.0 is meant to be used with babel 7, if you are using babel 6.x the correct version is 7.x
